bookweb/bookweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('greet.urls')),
    path('webofbooks/', include('webofbooks.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Configure Admin Titles
admin.site.site_header = "Web of Books Administration"
admin.site.site_title = "Web of Books"
admin.site.index_title = "Panel Admina"

bookweb/greet/urls.py
from django.urls import path

from greet import views

urlpatterns = [
    path('', views.hello),
]

bookweb/webofbooks/urls.py
from django.urls import path
from webofbooks.views import CountriesView, CountryCreateView, CountryUpdateView, CountryDeleteView, CountryDetailView, AuthorsView, AuthorCreateView, AuthorUpdateView, AuthorDetailView, AuthorDeleteView, CategoryView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView, CategoryDetailView, BookView, BookCreateView, BookDeleteView, BookDetailView, HomeView, update_book, search, booksreadadd, BooksReadView, BooksReadDeleteView, BooksInterestedView, BooksInterestedDeleteView, booksinterestedadd
from django.urls import include

app_name = 'webofbooks'

urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('countries/', CountriesView.as_view(), name='countries_list'),
    path('countries/create/', CountryCreateView.as_view(), name='country_create'),
    path('countries/update/<int:pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('countries/delete/<int:pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('countries/detail/<pk>/', CountryDetailView.as_view(), name='country_detail'),
    path('authors/', AuthorsView.as_view(), name='authors_list'),
    path('authors/create/', AuthorCreateView.as_view(), name='author_create'),
    path('authors/update/<int:pk>/', AuthorUpdateView.as_view(), name='author_update'),
    path('authors/detail/<pk>/', AuthorDetailView.as_view(), name='author_detail'),
    path('authors/delete/<int:pk>/', AuthorDeleteView.as_view(), name='author_delete'),
    path('categories/', CategoryView.as_view(), name='categories_list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('categories/detail/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('books/', BookView.as_view(), name='books_list'),
    path('books/create/', BookCreateView.as_view(), name='book_create'),
    path('books/update/<int:pk>/', update_book, name='book_update'),
    path('books/delete/<int:pk>/', BookDeleteView.as_view(), name='book_delete'),
    path('books/detail/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('search/', search, name='search'),
    path('user/booksread/', BooksReadView.as_view(), name='booksread_list'),
    path('user/booksread/delete/<int:pk>/', BooksReadDeleteView.as_view(), name='booksread_delete'),
    path('user/booksread/add/<int:pk>/', booksreadadd, name='booksread_add'),
    path('user/booksinterested/', BooksInterestedView.as_view(), name='booksinterested_list'),
    path('user/booksinterested/delete/<int:pk>/', BooksInterestedDeleteView.as_view(), name='booksinterested_delete'),
    path('user/booksinterested/add/<int:pk>/', booksinterestedadd, name='booksinterested_add'),

]

bookweb/webofbooks/models.py
from django.db import models
from django.db.models import ForeignKey, DO_NOTHING, DateField
from django.contrib.auth.models import User
from datetime import date
from django.urls import reverse




# Create your models here.
class Countries(models.Model):
    name = models.CharField(max_length=300, unique=True)

    def __str__(self):
        return f"{self.name}"

class Authors(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    date_of_death = models.DateField(null=True, blank=True)
    country = ForeignKey(Countries, on_delete=DO_NOTHING)

    def __str__(self):
        return f"{self.name}, {self.surname}, {self.date_of_birth}, {self.date_of_death}, {self.country}"

class Categories(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"

class Books(models.Model):
    author_id = ForeignKey(Authors, on_delete=DO_NOTHING, null=True)
    category_id = ForeignKey(Categories, on_delete=DO_NOTHING)
    title = models.CharField(max_length=300)
    issue_date = models.DateField()
    date_added = models.DateField(default=date.today)
    cover = models.ImageField(upload_to='', default='default.jpg')

    def __str__(self):
        return f"{self.date_added}{self.author_id}, {self.category_id}, {self.title}, {self.issue_date}, {self.cover}, {self.date_added}"

class BooksRead(models.Model):
    user_id = ForeignKey(User, on_delete=DO_NOTHING)
    book_id = ForeignKey(Books, on_delete=DO_NOTHING)

    def __str__(self):
        return f"{self.user_id}, {self.book_id}"

class BooksInterested(models.Model):
    user_id = ForeignKey(User, on_delete=DO_NOTHING)
    book_id = ForeignKey(Books, on_delete=DO_NOTHING)

    def __str__(self):
        return f"{self.user_id}, {self.book_id}"

bookweb/webofbooks/forms.py
from django.forms import (
  CharField, DateField, Form, IntegerField, ModelChoiceField, Textarea, ImageField, URLField, FileField, TextInput, DateInput, FileInput
)
from django.forms import ModelForm
from webofbooks.models import Countries, Authors, Categories, Books, BooksRead, BooksInterested
from datetime import date
from django.contrib.auth.models import User


class CountryForm(ModelForm):

  class Meta:
    model = Countries
    fields = '__all__'

    name = CharField(label="Nazwa", max_length=300)
    widgets = {
    'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Podaj nazwę kraju'}),
    }

class AuthorForm(ModelForm):
  class Meta:
    model = Authors
    fields = '__all__'

    name = CharField(max_length=100)
    surname = CharField(max_length=100)
    date_of_birth = DateField(label="Data urodzenia:")
    date_of_death = DateField(label="Data śmierci:", required=False)
    labels = {
    'name': 'Imię:',
    'surname': 'Nazwisko:',
    'date_of_birth': 'Data urodzenia:',
    'date_of_death': 'Data śmierci:'
    }
    widgets = {
    'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Imię autora'}),
    'surname': TextInput(attrs={'class': 'form-control', 'placeholder': 'Nazwisko autora'}),
    'date_of_birth': DateInput(attrs={'class': 'form-control', 'placeholder': '(rrrr-mm-dd)'}),
    'date_of_death': DateInput(attrs={'class': 'form-control', 'placeholder': '(rrrr-mm-dd)'}),
    }

class CategoryForm(ModelForm):

  class Meta:
    model = Categories
    fields = '__all__'
    name = CharField(label="Nazwa kategorii", max_length=100)
    labels = {
    'name': 'Kategoria:',
    }
    widgets = {
    'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Nazwa kategorii'}),
    }


class BookForm(ModelForm):
  class Meta:
    model = Books
    fields = '__all__'

    title = CharField(max_length=300)
    issue_date = DateField()
    cover = ImageField(required=False)
    labels = {
    'title': 'Tytuł:',
    'issue_date': 'Data wydania:',
    'cover': 'Okładka:',
    }
    widgets = {
    'title': TextInput(attrs={'class': 'form-control', 'placeholder': 'Podaj tytuł książki'}),
    'issue_date': DateInput(attrs={'class': 'form-control', 'placeholder': '(rrrr-mm-dd)'}),
    'cover': FileInput(attrs={'class': 'form-control'}),
    }

class BooksReadForm(ModelForm):
  class Meta:
    model = BooksRead
    fields = '__all__'

    user_id = CharField(disabled=True)
    book_id = CharField(disabled=True)

class BooksInterestedForm(ModelForm):
  class Meta:
    model = BooksInterested
    fields = '__all__'

    user_id = CharField(disabled=True)
    book_id = CharField(disabled=True)

bookweb/webofbooks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views import View
from django.views.generic import ListView, UpdateView
from django.views.generic.edit import FormView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.db.models import Q
from django.contrib.auth.models import User


from webofbooks.forms import CountryForm, AuthorForm, CategoryForm, BookForm, BooksReadForm, BooksInterestedForm
from webofbooks.models import Countries, Authors, Categories, Books, BooksRead, BooksInterested


class CountriesView(ListView):
    template_name = 'webofbooks/countries_list.html'
    model = Countries

class CountryCreateView(CreateView):
    template_name = 'webofbooks/countries_create_form.html'
    form_class = CountryForm
    success_url = reverse_lazy('webofbooks:countries_list')

class CountryUpdateView(UpdateView):
    template_name = 'webofbooks/countries_update_form.html'
    model = Countries
    success_url = reverse_lazy('webofbooks:countries_list')
    fields = ['name']

class CountryDeleteView(DeleteView):
  template_name = 'webofbooks/countries_delete_form.html'
  model = Countries
  success_url = reverse_lazy('webofbooks:countries_list')

class CountryDetailView(DetailView):
    def get(self, request, pk):
        return render(request,
                      'webofbooks/countries_detail.html',
                      context={
                          "country_authors": Authors.objects.filter(country_id=pk).all(),
                          "country": Countries.objects.filter(id=pk).all(),
                      })

class AuthorsView(ListView):
    template_name = 'webofbooks/authors_list.html'
    model = Authors

class AuthorCreateView(CreateView):
    template_name = 'webofbooks/authors_create_form.html'
    form_class = AuthorForm
    success_url = reverse_lazy('webofbooks:authors_list')

class AuthorUpdateView(UpdateView):
    template_name = 'webofbooks/authors_update_form.html'
    model = Authors
    success_url = reverse_lazy('webofbooks:authors_list')
    fields = ['name', 'surname', 'date_of_birth', 'date_of_death', 'country']

class AuthorDetailView(View):
    def get(self, request, pk):
        return render(request,
                      'webofbooks/authors_detail.html',
                      context={
                          "author_books": Books.objects.filter(author_id=pk).all(),
                          "author": Authors.objects.filter(id=pk).all(),
                      })

class AuthorDeleteView(DeleteView):
  template_name = 'webofbooks/authors_delete_form.html'
  model = Authors
  success_url = reverse_lazy('webofbooks:authors_list')

class CategoryView(ListView):
    template_name = 'webofbooks/categories_list.html'
    model = Categories

class CategoryCreateView(CreateView):
    template_name = 'webofbooks/categories_create_form.html'
    form_class = CategoryForm
    success_url = reverse_lazy('webofbooks:categories_list')

class CategoryUpdateView(UpdateView):
    template_name = 'webofbooks/categories_update_form.html'
    model = Categories
    success_url = reverse_lazy('webofbooks:categories_list')
    fields = ['name']

class CategoryDeleteView(DeleteView):
  template_name = 'webofbooks/categories_delete_form.html'
  model = Categories
  success_url = reverse_lazy('webofbooks:categories_list')

class CategoryDetailView(View):
    def get(self, request, pk):
        return render(request,
                      'webofbooks/categories_detail.html',
                      context={
                          "categories_books": Books.objects.filter(category_id=pk).all(),
                          "category": Categories.objects.filter(id=pk).all(),
                      })

class BookView(ListView):
    template_name = 'webofbooks/books_list.html'
    model = Books

class BookCreateView(CreateView):
    template_name = 'webofbooks/books_create_form.html'
    form_class = BookForm
    success_url = reverse_lazy('webofbooks:books_list')

def update_book(request, pk):
    this_book = Books.objects.get(id=pk)
    form = BookForm(request.POST or None, request.FILES or None, instance=this_book)
    if form.is_valid():
        form.save()
        return redirect('webofbooks:books_list')
    return render(request, 'webofbooks/books_update_form.html', context={
        "this_book": this_book,
        "form": form
    })

class BookDeleteView(DeleteView):
  template_name = 'webofbooks/books_delete_form.html'
  model = Books
  success_url = reverse_lazy('webofbooks:books_list')

class BookDetailView(DetailView):
    model = Books

class HomeView(View):
    def get(self, request):
        return render(request,
                      'webofbooks/webofbooks.html',
                      context={
                          "new_books": Books.objects.order_by('-date_added').all(),
                      })

def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        books_searched = Books.objects.filter(title__contains=searched)
        author_searched = Authors.objects.filter(Q(name__contains=searched) | Q(surname__contains=searched))

        return render(request,
                  'webofbooks/search.html',
                  context={'searched': searched,
                           'books_searched': books_searched,
                           'author_searched': author_searched})
    else:
        return render(request,
                  'webofbooks/search.html',
                  context={})

class BooksReadView(View):
    def get(self, request):
        username = request.user
        books_read = BooksRead.objects.filter(user_id=username).all()
        return render(request,
                      'webofbooks/user_booksread_list.html',
                      context={
                          "books_read": books_read,
                      })

class BooksReadDeleteView(DeleteView):
  template_name = 'webofbooks/user_booksread_delete_form.html'
  model = BooksRead
  success_url = reverse_lazy('webofbooks:booksread_list')


def booksreadadd(request, pk):
    this_book = Books.objects.get(id=pk)
    username = request.user
    data = {"user_id": username, "book_id": this_book}
    form = BooksReadForm(data)
    if form.is_valid():
        form.save()
        return redirect('webofbooks:booksread_list')
    return render(request, 'webofbooks/user_booksread_add_form.html', context={
        "book_id": this_book,
        "user_id": username,
        "form": form
    })

class BooksInterestedView(View):
    def get(self, request):
        username = request.user
        books_interested = BooksInterested.objects.filter(user_id=username).all()
        return render(request,
                      'webofbooks/user_booksinterested_list.html',
                      context={
                          "books_interested": books_interested,
                      })

class BooksInterestedDeleteView(DeleteView):
  template_name = 'webofbooks/user_booksinterested_delete_form.html'
  model = BooksInterested
  success_url = reverse_lazy('webofbooks:booksinterested_list')

def booksinterestedadd(request, pk):
    this_book = Books.objects.get(id=pk)
    username = request.user
    data = {"user_id": username, "book_id": this_book}
    form = BooksInterestedForm(data)
    if form.is_valid():
        form.save()
        return redirect('webofbooks:booksinterested_list')
    return render(request, 'webofbooks/user_interested_add_form.html', context={
        "book_id": this_book,
        "user_id": username,
        "form": form
    })

bookweb/webofbooks/templates/webofbooks/authors_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Witamy w świecie książek</title>
</head>
<body>
{% include 'webofbooks/navbar.html' %}
<h3>
{% for x in author %}
  {{ x.name }} {{ x.surname }}
{% endfor %}
</h3>

<ul>
  {% for book in author_books %}
    <li>
      <p>{{ book.title }} <a href="{% url 'webofbooks:book_detail' book.id %}"><button type="button" class="btn btn-success">Szczegóły</button></a></p>
    </li>
{% endfor %}
<br/>
<p><a href="{% url 'webofbooks:authors_list' %}"><button type="button" class="btn btn-secondary">Wróć do listy autorów</button></a></p>
<p><a href="{% url 'webofbooks:homepage' %}"><button type="button" class="btn btn-dark">Strona główna</button></a></p>

</body>
</html>

bookweb/webofbooks/templates/webofbooks/authors_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Witamy w świecie książek</title>
</head>
<body>
{% include 'webofbooks/navbar.html' %}
<h3>Lista autorów</h3>
<ol>
    {% for author in object_list %}
    <li>
        {{ author.name }} {{ author.surname }}
        <p><a href="{% url 'webofbooks:author_detail' author.id %}"><button type="button" class="btn btn-success">Pokaż książki autora</button></a></p>
        {% if user.is_superuser %}
        <p><a href="{% url 'webofbooks:author_update' author.id %}"><button type="button" class="btn btn-primary">Edytuj</button></a></p>
        <p><a href="{% url 'webofbooks:author_delete' author.id %}"><button type="button" class="btn btn-danger">Usuń</button></a></p>
        {% endif %}

    </li>
    {% endfor %}
</ol>

{% if user.is_superuser %}
<p><a href="{% url 'webofbooks:author_create' %}"><button type="button" class="btn btn-secondary">Dodaj autora do listy</button></a><p>
{% endif %}
<p><a href="{% url 'webofbooks:homepage' %}"><button type="button" class="btn btn-dark">Strona główna</button></a></p>
</body>
</html>

bookweb/webofbooks/templates/webofbooks/books_detail.html
{% load static %}
{% load ratings %}

<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<head>
  <title>Witamy w świecie książek</title>
</head>
<body>
{% include 'webofbooks/navbar.html' %}
    <p><b>Tytuł książki:</b> {{ object.title }}</p>
    <p><b>Autor:</b> {{ object.author_id.name }}  {{ object.author_id.surname }}</p>
    <p><b>Kategoria:</b> {{ object.category_id.name }}</p>
    <p><b>Data wydania:</b> {{ object.issue_date }}</p>
    <p><img style='max-width:100px' src="{% static object.cover.url %}"></p>
    <p>{% ratings object %}</p>


{% if user.is_authenticated %}
<p><a href="{% url 'webofbooks:booksread_add' object.id %}"><button type="button" class="btn btn-success">Przeczytałem tę książkę</button></a></p>
<p><a href="{% url 'webofbooks:booksinterested_add' object.id %}"><button type="button" class="btn btn-info">Chcę przeczytać tę książkę</button></a></p>
{% endif %}
<p><a href="{% url 'webofbooks:books_list' %}"><button type="button" class="btn btn-secondary">Wróć do listy</button></a></p>
<p><a href="{% url 'webofbooks:homepage' %}"><button type="button" class="btn btn-dark">Strona główna</button></a></p>

</body>
</html>

bookweb/webofbooks/templates/webofbooks/books_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Witamy w świecie książek</title>
</head>
<body>
{% include 'webofbooks/navbar.html' %}
<h3>Lista książek</h3>
<ol>
    {% for book in object_list %}
    <li>
        <p><img style='max-width:100px' src="{% static book.cover.url %}"></p>
        <p><b>Tytuł:</b> {{ book.title }}</p>
        <p><b>Autor:</b> {{ book.author_id.name }} {{ book.author_id.surname }}</p>
        <div>
            <a href="{% url 'webofbooks:book_detail' book.id %}"><button type="button" class="btn btn-success">Szczegóły</button></a>
            {% if user.is_superuser %}
            <a href="{% url 'webofbooks:book_update' book.id %}"><button type="button" class="btn btn-primary">Edytuj</button></a>
            <a href="{% url 'webofbooks:book_delete' book.id %}"><button type="button" class="btn btn-danger">Usuń</button></a>
            {% endif %}

        </div>
    </li>
    {% endfor %}
</ol>

{% if user.is_superuser %}
<p><a href="{% url 'webofbooks:book_create' %}"><button type="button" class="btn btn-secondary">Dodaj książkę</button></a></p>
{% endif %}
<p><a href="{% url 'webofbooks:homepage' %}"><button type="button" class="btn btn-dark">Strona główna</button></a></p>
</body>
</html>

bookweb/webofbooks/templates/webofbooks/countries_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Witamy w świecie książek</title>
</head>
<body>
{% include 'webofbooks/navbar.html' %}
<h3>Lista krajów</h3>
<ol>
    {% for country in object_list %}
    <li>
        {{ country.name }}
        <div>
        <a href="{% url 'webofbooks:country_detail' country.id %}"><button type="button" class="btn btn-success">Pokaż autorów</button></a>
        {% if user.is_superuser %}
        <a href="{% url 'webofbooks:country_update' country.id %}"><button type="button" class="btn btn-primary">Edytuj nazwę kraju</button></a>
        <a href="{% url 'webofbooks:country_delete' country.id %}"><button type="button" class="btn btn-danger">Usuń kraj z listy</button></a>
        {% endif %}
        </div>
    </li>
    {% endfor %}
</ol>

{% if user.is_superuser %}
<p><a href="{% url 'webofbooks:country_create' %}"><button type="button" class="btn btn-secondary">Dodaj kraj</button></a></p>
{% endif %}
<p><a href="{% url 'webofbooks:homepage' %}"><button type="button" class="btn btn-dark">Strona główna</button></a></p>


</body>
</html>

bookweb/webofbooks/templates/webofbooks/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <title>Witamy w świecie książek</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body class="p-3 m-0 border-0 bd-example">
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'webofbooks:homepage' %}">WebOfBooks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Autorzy
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'webofbooks:authors_list' %}">Lista autorów</a></li>
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="{% url 'webofbooks:author_create' %}">Dodaj autora</a></li>
            {% endif %}
          </ul>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Książki
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'webofbooks:books_list' %}">Lista książek</a></li>
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="{% url 'webofbooks:book_create' %}">Dodaj książkę</a></li>
            {% endif %}
          </ul>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Kategorie
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'webofbooks:categories_list' %}">Lista kategorii</a></li>
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="{% url 'webofbooks:category_create' %}">Dodaj kategorię</a></li>
            {% endif %}
          </ul>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Kraje
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'webofbooks:countries_list' %}">Lista krajów</a></li>
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="{% url 'webofbooks:country_create' %}">Dodaj kraj</a></li>
            {% endif %}
          </ul>
        </li>

      <form class="d-flex" role="search" method="POST" action="{% url 'webofbooks:search' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Wyszukaj frazę" aria-label="Search" name="searched">
        <button class="btn btn-outline-secondary" type="submit">Szukaj</button>
      </form>
                {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.get_username }}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'webofbooks:booksread_list' %}">Przeczytane książki</a></li>
            <li><a class="dropdown-item" href="{% url 'webofbooks:booksinterested_list' %}">Chcę przeczytać</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class = "nav-link" href="{% url 'logout' %}">Wyloguj się</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class = "nav-link" href="{% url 'register_user' %}">Zarejestruj się</a>
        </li>
        <li class="nav-item">
          <a class = "nav-link" href="{% url 'login' %}">Zaloguj się</a>
        </li>
        {% endif %}
    </div>
  </div>
</nav>
<body>

</body>
</html>

bookweb/webofbooks/templates/webofbooks/user_booksread_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista przeczytanych książek</title>
</head>
<body>
{% include 'webofbooks/navbar.html' %}
<h3>Twoja lista przeczytanych książek</h3>
<ol>
    {% for book in books_read %}
    <li>
        <p><img style='max-width:100px' src="{% static book.book_id.cover.url %}"></p>
        <p><b>Tytuł:</b> {{ book.book_id.title }}</p>
        <p><b>Autor:</b> {{ book.book_id.author_id.name }} {{ book.book_id.author_id.surname }}</p>
    </li>
    <a href="{% url 'webofbooks:booksread_delete' book.id %}"><button type="button" class="btn btn-danger">Usuń</button></a>
    {% endfor %}
</ol>

<p><a href="{% url 'webofbooks:homepage' %}"><button type="button" class="btn btn-dark">Strona główna</button></a></p>
</body>
</html>